// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class EmailsController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _EmailLayout = "_EmailLayout";
                public readonly string _JobHeader = "_JobHeader";
                public readonly string _ViewStart = "_ViewStart";
                public readonly string JobComplete = "JobComplete";
                public readonly string JobHasBeenPicked = "JobHasBeenPicked";
                public readonly string ReadyToPick = "ReadyToPick";
            }
            public readonly string _EmailLayout = "~/Views/Emails/_EmailLayout.cshtml";
            public readonly string _JobHeader = "~/Views/Emails/_JobHeader.cshtml";
            public readonly string _ViewStart = "~/Views/Emails/_ViewStart.cshtml";
            public readonly string JobComplete = "~/Views/Emails/JobComplete.cshtml";
            public readonly string JobHasBeenPicked = "~/Views/Emails/JobHasBeenPicked.cshtml";
            public readonly string ReadyToPick = "~/Views/Emails/ReadyToPick.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string Address = "Address";
                public readonly string AssetKind = "AssetKind";
                public readonly string DateTime = "DateTime";
                public readonly string JobStatus = "JobStatus";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
