// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mavo.Assets.Controllers
{
    public partial class JobController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected JobController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddOnModal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOnModal);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CreateAddon()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateAddon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TransferAssetsModal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferAssetsModal);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TransferAssets()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferAssets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddAssetsFromTemplate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAssetsFromTemplate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Create()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveSummary()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSummary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult MarkReadyToPick()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkReadyToPick);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JobController Actions { get { return MVC.Job; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Job";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Job";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AddOnModal = "AddOnModal";
            public readonly string CreateAddon = "CreateAddon";
            public readonly string TransferAssetsModal = "TransferAssetsModal";
            public readonly string TransferAssets = "TransferAssets";
            public readonly string Index = "Index";
            public readonly string AddAssetsFromTemplate = "AddAssetsFromTemplate";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string SaveSummary = "SaveSummary";
            public readonly string MarkReadyToPick = "MarkReadyToPick";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AddOnModal = "AddOnModal";
            public const string CreateAddon = "CreateAddon";
            public const string TransferAssetsModal = "TransferAssetsModal";
            public const string TransferAssets = "TransferAssets";
            public const string Index = "Index";
            public const string AddAssetsFromTemplate = "AddAssetsFromTemplate";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string SaveSummary = "SaveSummary";
            public const string MarkReadyToPick = "MarkReadyToPick";
        }


        static readonly ActionParamsClass_AddOnModal s_params_AddOnModal = new ActionParamsClass_AddOnModal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddOnModal AddOnModalParams { get { return s_params_AddOnModal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddOnModal
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CreateAddon s_params_CreateAddon = new ActionParamsClass_CreateAddon();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateAddon CreateAddonParams { get { return s_params_CreateAddon; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateAddon
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TransferAssetsModal s_params_TransferAssetsModal = new ActionParamsClass_TransferAssetsModal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransferAssetsModal TransferAssetsModalParams { get { return s_params_TransferAssetsModal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransferAssetsModal
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TransferAssets s_params_TransferAssets = new ActionParamsClass_TransferAssets();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransferAssets TransferAssetsParams { get { return s_params_TransferAssets; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransferAssets
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string status = "status";
            public readonly string customerId = "customerId";
            public readonly string projectManagerId = "projectManagerId";
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_AddAssetsFromTemplate s_params_AddAssetsFromTemplate = new ActionParamsClass_AddAssetsFromTemplate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAssetsFromTemplate AddAssetsFromTemplateParams { get { return s_params_AddAssetsFromTemplate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAssetsFromTemplate
        {
            public readonly string id = "id";
            public readonly string templateId = "templateId";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string templateId = "templateId";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string jobPostModel = "jobPostModel";
        }
        static readonly ActionParamsClass_SaveSummary s_params_SaveSummary = new ActionParamsClass_SaveSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSummary SaveSummaryParams { get { return s_params_SaveSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSummary
        {
            public readonly string id = "id";
            public readonly string jobPostModel = "jobPostModel";
        }
        static readonly ActionParamsClass_MarkReadyToPick s_params_MarkReadyToPick = new ActionParamsClass_MarkReadyToPick();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MarkReadyToPick MarkReadyToPickParams { get { return s_params_MarkReadyToPick; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MarkReadyToPick
        {
            public readonly string jobId = "jobId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _JobAlerts = "_JobAlerts";
                public readonly string _JobSidebar = "_JobSidebar";
                public readonly string _SearchResult = "_SearchResult";
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
            }
            public readonly string _JobAlerts = "~/Views/Job/_JobAlerts.cshtml";
            public readonly string _JobSidebar = "~/Views/Job/_JobSidebar.cshtml";
            public readonly string _SearchResult = "~/Views/Job/_SearchResult.cshtml";
            public readonly string Edit = "~/Views/Job/Edit.cshtml";
            public readonly string Index = "~/Views/Job/Index.cshtml";
            static readonly _ModalsClass s_Modals = new _ModalsClass();
            public _ModalsClass Modals { get { return s_Modals; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ModalsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AddCustomerModal = "_AddCustomerModal";
                    public readonly string _AddForemanModal = "_AddForemanModal";
                    public readonly string _AddOnModal = "_AddOnModal";
                    public readonly string _AddProjectManagerModal = "_AddProjectManagerModal";
                    public readonly string _PickJobModal = "_PickJobModal";
                    public readonly string _TransferAssetModal = "_TransferAssetModal";
                }
                public readonly string _AddCustomerModal = "~/Views/Job/Modals/_AddCustomerModal.cshtml";
                public readonly string _AddForemanModal = "~/Views/Job/Modals/_AddForemanModal.cshtml";
                public readonly string _AddOnModal = "~/Views/Job/Modals/_AddOnModal.cshtml";
                public readonly string _AddProjectManagerModal = "~/Views/Job/Modals/_AddProjectManagerModal.cshtml";
                public readonly string _PickJobModal = "~/Views/Job/Modals/_PickJobModal.cshtml";
                public readonly string _TransferAssetModal = "~/Views/Job/Modals/_TransferAssetModal.cshtml";
            }
            static readonly _TabsClass s_Tabs = new _TabsClass();
            public _TabsClass Tabs { get { return s_Tabs; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _TabsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AssetHistory = "_AssetHistory";
                    public readonly string _DataSheet = "_DataSheet";
                    public readonly string _JobSummary = "_JobSummary";
                    public readonly string _PickList = "_PickList";
                }
                public readonly string _AssetHistory = "~/Views/Job/Tabs/_AssetHistory.cshtml";
                public readonly string _DataSheet = "~/Views/Job/Tabs/_DataSheet.cshtml";
                public readonly string _JobSummary = "~/Views/Job/Tabs/_JobSummary.cshtml";
                public readonly string _PickList = "~/Views/Job/Tabs/_PickList.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_JobController : Mavo.Assets.Controllers.JobController
    {
        public T4MVC_JobController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AddOnModal(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOnModal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateAddon(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateAddon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TransferAssetsModal(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferAssetsModal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TransferAssets(Mavo.Assets.Models.ViewModel.TransferAssetsViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferAssets);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(Mavo.Assets.Models.JobStatus? status, int? customerId, int? projectManagerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "status", status);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectManagerId", projectManagerId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddAssetsFromTemplate(int id, int templateId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAssetsFromTemplate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(Mavo.Assets.Models.ViewModel.SearchResult search)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(int? templateId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateId", templateId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveSummary(int id, Mavo.Assets.Models.ViewModel.EditJobPostModel jobPostModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jobPostModel", jobPostModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(Mavo.Assets.Models.ViewModel.EditJobPostModel jobPostModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jobPostModel", jobPostModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MarkReadyToPick(int jobId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MarkReadyToPick);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jobId", jobId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
