// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mavo.Assets.Controllers
{
    public partial class JobReturnerController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected JobReturnerController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Cancel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cancel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult StartReturning()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.StartReturning);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Success()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Success);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CompleteReturning()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompleteReturning);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JobReturnerController Actions { get { return MVC.JobReturner; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "JobReturner";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "JobReturner";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Cancel = "Cancel";
            public readonly string StartReturning = "StartReturning";
            public readonly string Index = "Index";
            public readonly string Success = "Success";
            public readonly string CompleteReturning = "CompleteReturning";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Cancel = "Cancel";
            public const string StartReturning = "StartReturning";
            public const string Index = "Index";
            public const string Success = "Success";
            public const string CompleteReturning = "CompleteReturning";
        }


        static readonly ActionParamsClass_Cancel s_params_Cancel = new ActionParamsClass_Cancel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Cancel CancelParams { get { return s_params_Cancel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Cancel
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_StartReturning s_params_StartReturning = new ActionParamsClass_StartReturning();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StartReturning StartReturningParams { get { return s_params_StartReturning; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StartReturning
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
            public readonly string assets = "assets";
        }
        static readonly ActionParamsClass_Success s_params_Success = new ActionParamsClass_Success();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Success SuccessParams { get { return s_params_Success; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Success
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CompleteReturning s_params_CompleteReturning = new ActionParamsClass_CompleteReturning();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CompleteReturning CompleteReturningParams { get { return s_params_CompleteReturning; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CompleteReturning
        {
            public readonly string jobId = "jobId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _JobReturnerSidebar = "_JobReturnerSidebar";
                public readonly string _ReturnerLayout = "_ReturnerLayout";
                public readonly string Index = "Index";
                public readonly string Success = "Success";
                public readonly string TabletReturner = "TabletReturner";
            }
            public readonly string _JobReturnerSidebar = "~/Views/JobReturner/_JobReturnerSidebar.cshtml";
            public readonly string _ReturnerLayout = "~/Views/JobReturner/_ReturnerLayout.cshtml";
            public readonly string Index = "~/Views/JobReturner/Index.cshtml";
            public readonly string Success = "~/Views/JobReturner/Success.cshtml";
            public readonly string TabletReturner = "~/Views/JobReturner/TabletReturner.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_JobReturnerController : Mavo.Assets.Controllers.JobReturnerController
    {
        public T4MVC_JobReturnerController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Cancel(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cancel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult StartReturning(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.StartReturning);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(int id, System.Collections.Generic.IList<Mavo.Assets.Models.ViewModel.JobAsset> assets)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "assets", assets);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Success(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Success);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CompleteReturning(int jobId, string @continue)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompleteReturning);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jobId", jobId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "continue", @continue);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
