// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mavo.Assets.Controllers
{
    public partial class ReportingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportingController Actions { get { return MVC.Reporting; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Reporting";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Reporting";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string LateJobs = "LateJobs";
            public readonly string Jobs = "Jobs";
            public readonly string AssetHistory = "AssetHistory";
            public readonly string AssetHistoryFilter = "AssetHistoryFilter";
            public readonly string FellOffTruck = "FellOffTruck";
            public readonly string TomorrowsPicks = "TomorrowsPicks";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string LateJobs = "LateJobs";
            public const string Jobs = "Jobs";
            public const string AssetHistory = "AssetHistory";
            public const string AssetHistoryFilter = "AssetHistoryFilter";
            public const string FellOffTruck = "FellOffTruck";
            public const string TomorrowsPicks = "TomorrowsPicks";
        }


        static readonly ActionParamsClass_AssetHistoryFilter s_params_AssetHistoryFilter = new ActionParamsClass_AssetHistoryFilter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AssetHistoryFilter AssetHistoryFilterParams { get { return s_params_AssetHistoryFilter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AssetHistoryFilter
        {
            public readonly string id = "id";
            public readonly string userId = "userId";
            public readonly string date = "date";
            public readonly string startDate = "startDate";
            public readonly string endDate = "endDate";
        }
        static readonly ActionParamsClass_FellOffTruck s_params_FellOffTruck = new ActionParamsClass_FellOffTruck();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FellOffTruck FellOffTruckParams { get { return s_params_FellOffTruck; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FellOffTruck
        {
            public readonly string startDate = "startDate";
            public readonly string endDate = "endDate";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AssetHistoryResults = "_AssetHistoryResults";
                public readonly string _ReadyJob = "_ReadyJob";
                public readonly string AssetHistory = "AssetHistory";
                public readonly string FellOffTruck = "FellOffTruck";
                public readonly string Jobs = "Jobs";
                public readonly string LateJobs = "LateJobs";
                public readonly string TomorrowsPicks = "TomorrowsPicks";
            }
            public readonly string _AssetHistoryResults = "~/Views/Reporting/_AssetHistoryResults.cshtml";
            public readonly string _ReadyJob = "~/Views/Reporting/_ReadyJob.cshtml";
            public readonly string AssetHistory = "~/Views/Reporting/AssetHistory.cshtml";
            public readonly string FellOffTruck = "~/Views/Reporting/FellOffTruck.cshtml";
            public readonly string Jobs = "~/Views/Reporting/Jobs.cshtml";
            public readonly string LateJobs = "~/Views/Reporting/LateJobs.cshtml";
            public readonly string TomorrowsPicks = "~/Views/Reporting/TomorrowsPicks.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ReportingController : Mavo.Assets.Controllers.ReportingController
    {
        public T4MVC_ReportingController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult LateJobs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LateJobs);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Jobs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Jobs);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AssetHistory()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssetHistory);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AssetHistoryFilter(string id, int? userId, System.DateTime? date, System.DateTime? startDate, System.DateTime? endDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssetHistoryFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "date", date);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "startDate", startDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "endDate", endDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult FellOffTruck(System.DateTime? startDate, System.DateTime? endDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FellOffTruck);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "startDate", startDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "endDate", endDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TomorrowsPicks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TomorrowsPicks);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
