// <auto-generated />
namespace Mavo.Assets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RelationshipForAssetItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationshipForAssetItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201212072038579_RelationshipForAssetItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
