// <auto-generated />
namespace Mavo.Assets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class JobAddedForman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobAddedForman));
        
        string IMigrationMetadata.Id
        {
            get { return "201212052206158_Job-AddedForman"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
