// <auto-generated />
namespace Mavo.Assets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class whatup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatup));
        
        string IMigrationMetadata.Id
        {
            get { return "201212181704121_whatup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
