// <auto-generated />
namespace Mavo.Assets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Jobsv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jobsv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201212052024149_Jobs-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
