// <auto-generated />
namespace Mavo.Assets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GH170 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GH170));
        
        string IMigrationMetadata.Id
        {
            get { return "201306242013031_GH170"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
